# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adarsh Jamadandi
full_name: Adarsh Jamadandi
email: adarsh.jam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adarshmj.github.io" # the base hostname & protocol for your site
github_username:  adarshmj
twitter_username: adarshjamadandi
linkedin_username: adarsh-jamadandi
include: ['_pages']

# Build settings
markdown: kramdown
